In [1]:
import gym
from gym import Env
from gym.spaces import Discrete, Box, Dict, Tuple, MultiBinary, MultiDiscrete

import numpy as np
import random
import os

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
Discrete(3).sample()

1

In [7]:
Box(0,1, shape = (3,3)).sample()

array([[0.3283875 , 0.16138119, 0.10162533],
       [0.8883023 , 0.8908143 , 0.7757856 ],
       [0.23789398, 0.27295926, 0.9179189 ]], dtype=float32)

In [9]:
Tuple((Discrete(3), Box(0,1, shape= (3,3)))).sample()

(1,
 array([[0.7824584 , 0.8827193 , 0.44119972],
        [0.14470485, 0.40930188, 0.49354118],
        [0.89573216, 0.27451235, 0.8343408 ]], dtype=float32))

In [12]:
Dict({"height": Discrete(2), "speed": Box(0,100, shape = (1,))})

Dict('height': Discrete(2), 'speed': Box(0.0, 100.0, (1,), float32))

In [13]:
MultiBinary(4).sample()

array([1, 0, 1, 1], dtype=int8)

In [18]:
MultiDiscrete([5,2,2]).sample()

array([1, 0, 1])

In [33]:
class ShowerEnv(Env):
    def __init__(self):
        self.action_space = Discrete(3)
        self.observation_space = Box(low= np.array([0]), high= np.array([100]))
        self.state = 35 + random.randint(-3,3)
        self.shower_length = 60
        
    def step(self,action):
        self.state += action-1
        self.shower_length -=1

        if self.state >= 37 and self.state <= 39:
            reward = 1
        else:
            reward = -1
        if self.shower_length <=0:
            done=True
        else:
            done = False

        info = {}

        return self.state, reward, done, info
    def render(self):
        pass
    def reset(self):
        self.state = np.array([38 + random.randint(-3,3)]).astype(float)
        self.shower_length = 60
        return self.state

In [34]:
env = ShowerEnv()

In [35]:
env.observation_space.sample()

array([36.819157], dtype=float32)

In [36]:
env.action_space.sample()

1

In [37]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score+=reward
    print('Episode:{} Score:{}'.format(episode, score))
env.close()

Episode:1 Score:-40
Episode:2 Score:-10
Episode:3 Score:-8
Episode:4 Score:-8
Episode:5 Score:-12


In [42]:
log_path = os.path.join('Training', 'Logs')


In [43]:
model = PPO("MlpPolicy", env, verbose=1, tensorboard_log=log_path)


Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [45]:
model.learn(total_timesteps=4000)

ValueError: not enough values to unpack (expected 2, got 1)